Dev
ProfessorLayton322/vcl_rust pull request #1
Opened 2024-05-09 20:02 UTC by ProfessorLayton322

2024-05-12 17:33 UTC, asokol123 requested changes
1) надо прогнать clippy и cargo fmt, форматирование ужас. CI этого не сделало, потому что оно только на пуш в main (зачем?)
2) сделать так, чтобы было удобно работать с библиотекой. Сейчас вообще нет никаких экспортируемых типов, и использовать нельзя никак) Надо сделать так, чтобы я мог написать `use vcl_rust::Vec128f`, и это автоматически будет хороший тип, который поддерживается
3) сделать нормальные ошибки компиляции. Сейчас я на arm запустил `cargo clippy`, и у меня упала компиляция с сообщением об отсутствующих методах. Надо либо хорошее сообщение об ошибке, если процессор не поддерживается, либо чтобы всегда компилилось
4) нормальные названия функция и документация
5) UNSAFE!!! Если, используя библиотеку, можно добиться UB без написания слова unsafe, это значит что библиотека unsound. Такого быть не должно. + надо safety comment, у каждой unsafe функции он должен описывать, какие требования должен соблюсти тот, кто ее вызывает, у unsafe блока он должен объяснять, почему его вызывать безопасно (например у тебя много проблем при работе с указателями, там UB на UB)

2024-05-12 17:33 UTC, asokol123 commented on src/lib.rs
> +mod vectorf128;
Тут явно нужны `pub mod` или что-то такое
Потому что сейчас из твоей библиотеки наружу ничего не торчит, и пользователь не может ничего использовать

2024-05-12 17:33 UTC, asokol123 commented on src/lib.rs
> +fn compare_vec4f(vec: &Vec4f, a: f32, b: f32, c: f32, d: f32) {
Лучше принимать не четыре флота, а массив из четырех f32

2024-05-12 17:33 UTC, asokol123 commented on src/lib.rs
> +fn test_basic() {
Тесты надо вынести в `mod tests`, который включается только если `cfg(tests)`
Тогда они не будут компилироваться в обычных бинарях

2024-05-12 17:33 UTC, asokol123 commented on src/lib.rs
> +fn compare_vec4f(vec: &Vec4f, a: f32, b: f32, c: f32, d: f32) {
И вообще, зачем это?
Почему не сделать `impl PartialEq<[f32; 4]> for Vec4f`
И тогда можно будет просто писать дальше `assert_eq!(vec4f_val, [a, b, c, d])`

2024-05-12 17:33 UTC, asokol123 commented on src/vectorf128.rs
> +pub mod vec128 {
Очень плохо (
Надо вынести в отдельный файл, который будет подключаться (через mod) только при этом cfg
И в нем добавить ошибку компиляции еще если условия не выполнены

Сейчас у тебя не ошибка компиляции, а просто нет функций/структур - это сильно неожидаемое поведение, так быть не должно

2024-05-12 17:33 UTC, asokol123 commented on src/vectorf128.rs
> +    pub fn selectf(s: __m128, a: __m128, b: __m128) -> __m128 {
Иметь публичную функцию, работающую с `__m128` - странно
`__m128` - внутренний тип, с которым неудобно работать, он не должен торчать в публичных интерфейсах нигде (а еще он платформо зависимый)

2024-05-12 17:33 UTC, asokol123 commented on src/vectorf128.rs
> +        pub fn store(self, p: *mut f32) {
Эта функция явно должна быть `unsafe`!!
Если, вызвав функцию, можно получить UB, то она должна быть помечена unsafe, и прописаны условия, какие должен соблюдать вызывающий

2024-05-12 17:33 UTC, asokol123 commented on src/vectorf128.rs
> +        pub fn store(self, p: *mut f32) {
Добавить функции, работающие с ссылками на слайсы/массивы, а не сырыми указателями
Указатели в расте не используются почти никогда

2024-05-12 17:33 UTC, asokol123 commented on src/vectorf128.rs
> +        pub fn store_a(self, p: *mut f32) {
Название вообще ничего не говорит
Я предполагаю, что a - aligned, но не удивлюсь, если на самом деле это store_alien

2024-05-12 17:33 UTC, asokol123 commented on src/vectorf128.rs
> +        pub fn store_nt(self, p: *mut f32) {
А это store nice try?

2024-05-12 17:33 UTC, asokol123 commented on src/vectorf128.rs
> +        pub fn extract(&self, index: usize) -> f32 {
Кажется, скорее `get`
extract выглядит как "достань и удали"

2024-05-12 17:33 UTC, asokol123 commented on src/vectorf128.rs
> +        pub const fn size() -> usize {
Почему это не associated const?

2024-05-12 17:33 UTC, asokol123 commented on src/vectorf128.rs
> +    pub fn square(vec: Vec4f) -> Vec4f {
А почему это не метод?
В математике мы пишем x^2, тут тоже было бы логичнее `x.squared()` (IMO)

2024-05-12 17:33 UTC, asokol123 commented on src/vectorf128.rs
> +    pub fn pow(mut vec: Vec4f, mut n: i32) -> Vec4f {
Тоже как метод - заодно будет [консистентно](https://doc.rust-lang.org/std/primitive.i32.html#method.pow) со стандартными типами

2024-05-12 17:33 UTC, asokol123 commented on src/vectorf128e.rs
> +pub struct Vec4f {
А смысл этой структуры если нет никаких методов?
Плюс надо явно сделать публичный тип, который автоматически выбирается как более эффективный из двух поддерживаемых

2024-05-12 19:07 UTC, ProfessorLayton322 commented on src/vectorf128.rs
> +        pub fn store_a(self, p: *mut f32) {
https://github.com/vectorclass/version2/blob/f4617df57e17efcd754f5bbe0ec87883e0ed9ce6/vectorf128.h#L532

Я оставил то же самое название, что в vcl

Я правильно понимаю, что внутренняя разумность наименований > консистентность с исходными названиями в портируемой либе?

2024-05-12 19:08 UTC, ProfessorLayton322 commented on src/vectorf128.rs
> +        pub fn store_nt(self, p: *mut f32) {
То же самое
https://github.com/vectorclass/version2/blob/f4617df57e17efcd754f5bbe0ec87883e0ed9ce6/vectorf128.h#L539

2024-05-13 05:51 UTC, ProfessorLayton322 commented on src/vectorf128.rs
> +        pub fn store(self, p: *mut f32) {
Мне кажется имеет смысл сделать эту функцию safe, которая проверяет, что в слайсе хватает места. И unsafe, которая не проверяет

Примерно как get и get_unchecked у слайсов/векторов

2024-05-13 07:33 UTC, ProfessorLayton322 commented on src/vectorf128e.rs
> +pub struct Vec4f {
Вообще планировалось сделать его просто как вектор с четырьмя флотами, который компилировался бы вообще на любой архитектуре

Но я не уверен, насколько это хорошая идея, возможно стоит просто его выкинуть :/

2024-05-20 07:32 UTC, asokol123 requested changes

2024-05-20 07:32 UTC, asokol123 commented on benches/vcl_benchmark.rs
> +fn div(n: u32) {
Так бенчмарки писать нельзя. Компилятор имеет полное право соптимизировать эту функцию в пустоту (и я крайне удивлен что он так не делает в релизе)
Надо как минимум вернуть результат

2024-05-20 07:32 UTC, asokol123 commented on docs/crates.js
> +window.ALL_CRATES = ["vcl_rust"];
Документация не должна заливаться в репозиторий

2024-05-20 07:32 UTC, asokol123 commented on src/lib.rs
> +//mod vectorf128e;
Комментариев с кодом в финальной версии кода быть не должно

2024-05-20 07:32 UTC, asokol123 commented on src/lib.rs
> +pub mod vectorf128;
А почему не сделать `pub use vectorf128::*`?
Кажется, пользователям должно стать строго удобнее

2024-05-20 07:32 UTC, asokol123 commented on src/vectorf128.rs
> +#[cfg(not(any(target_arch = "x86", target_arch = "x86_64")))]
А зачем это тут?
Вроде `mod vectorf128` и так под этим cfg находится, значит без него не будет компилиться

2024-05-20 07:32 UTC, asokol123 commented on src/vectorf128.rs
> +use std::arch::x86::*;
Кстати можно сделать `use std::arch::x86 as intrinsics` в `lib.rs` чтобы везде не писать эти 4 строчки, и использовать как `crate::intrinsics::*` везде

Это не issue, так, предложение на будущее

2024-05-20 07:32 UTC, asokol123 commented on src/vectorf128.rs
> +use std::option::Option;
И кстати, этот крейт можно сделать `no_std`, потому что везде используется только `core` на самом деле

2024-05-20 07:32 UTC, asokol123 commented on src/vectorf128.rs
> +/// This struct is a wrapper around [__m128](https://doc.rust-lang.org/core/arch/x86/struct.__m128.html) intrinsic (or the same intrinsic from `x86_64` arch)
Документация бессмысленна сейчас. Что внутри - не важно, важно, что это структура хранит 4 f32 упакованно для simd инструкций

2024-05-20 07:32 UTC, asokol123 commented on src/vectorf128.rs
> +            //sse
rustfmt
А лучше в честном SAFETY формате (`/// SAFETY: sse`)

2024-05-20 07:32 UTC, asokol123 commented on src/vectorf128.rs
> +#[derive(Clone, Debug, Copy)]
Не лучше `Debug` руками реализовать? Кажется, сейчас будет выводиться как `Vec4f(одно большое число)`
А удобнее явно как `Vec4f([1, 2, 3, 4])`
Или хотя бы как `Vec4f(hex)`

2024-05-20 07:32 UTC, asokol123 commented on src/vectorf128.rs
> +            if (n & 1) > 0 {
А почему не `% 2` и `/= 2`?
Компиляторы же явно достаточно умные для этого давно, а код станет сильно более читаем

2024-05-20 07:32 UTC, asokol123 commented on src/vectorf128.rs
> +    /// a = a.insert(0, 6.0);
Я бы поменял в примере порядок этих `insert`, сейчас сложнее понять, оно сдвигает, или присваивает (да, написано, но надо включать мозги)

2024-05-20 07:32 UTC, asokol123 commented on src/vectorf128.rs
> +        let float_pointer: *const f32 = unsafe { std::mem::transmute(&self.xmm as *const __m128) };
Здесь лучше просто кастить указатели - `&self.xmm as *const __m128 as *const f32`

2024-05-20 07:32 UTC, asokol123 commented on src/vectorf128.rs
> +        unsafe { &*(float_pointer.add(index)) }
Это надо запустить под `miri`, я хз, законно ли так. Всегда делал через `.as_ref`

2024-05-20 07:32 UTC, asokol123 commented on src/vectorf128.rs
> +    pub fn truncate(self) -> Self {
А почему это закомментировано? Не работает?
В любом случае комментариев с кодом быть не должно

2024-05-20 07:32 UTC, asokol123 commented on src/vectorf128.rs
> +        let mask: __m128 = unsafe { _mm_castsi128_ps(_mm_set1_epi32(0x7FFFFFFF)) };
`i32::MAX`

2024-05-20 07:32 UTC, asokol123 commented on src/vectorf128.rs
> +        arr == *other
А эффективнее никак?..

2024-05-20 09:17 UTC, ProfessorLayton322 commented on src/vectorf128.rs
> +    pub fn truncate(self) -> Self {
Мне казалось что там необходим булев вектор чтобы оно работало, но кажется это не так :/

2024-05-21 03:19 UTC, ProfessorLayton322 commented on src/vectorf128.rs
> +        unsafe { &*(float_pointer.add(index)) }
Переделал на as_ref

2024-05-21 03:54 UTC, ProfessorLayton322 commented on src/vectorf128.rs
> +#[derive(Clone, Debug, Copy)]
Да нет, сейчас оно выглядит как Vec4f { xmm: __m128(1.0, 2.0, 3.0, 4.0) } например

2024-05-21 13:03 UTC, asokol123 approved these changes

2024-05-21 13:12 UTC, merged